# Generated by Django 3.2.4 on 2021-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
